# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "homeassistant/aarch64-base-ubuntu:20.04"
  amd64: "homeassistant/amd64-base-ubuntu:20.04"
  armhf: "homeassistant/armhf-base-ubuntu:20.04"
  armv7: "homeassistant/armv7-base-ubuntu:20.04"
  i386: "homeassistant/i386-base-ubuntu:20.04"
args:
  BINARY_IMAGE: "ghcr.io/simulatan/uwz:latest"
